server:
  port: 3200

spring:
  application:
    name: OKTA-GATEWAY
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa53fszc8BniObKG5d7
            client-secret: -rUBX_6MC-Z3BQ0GGY0uZBXpgbbRQ-8ptvTFzvH7
            redirect-uri: http://localhost:3200/login/oauth2/code/okta
        provider:
          okta:
            authorization-uri: https://dev-36737928.okta.com/oauth2/v1/authorize
            token-uri: https://dev-36737928.okta.com/oauth2/v1/token
            user-info-uri: https://dev-36737928.okta.com/oauth2/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://dev-36737928.okta.com/oauth2/v1/keys